### PR TITLE
Fix name of emitted scrollEnd event

### PR DESCRIPTION
**Pull request by jmarceli**
"scrollEnd" event fix.
README update.

### CODE REVIEW

**Comment by jmarceli** [comment]
It seems that in order to pass Codacy analysis `dev-master` branch should be enabled.

**Comment by xobotyi** [comment]
Actually i've just missed that row when changed the name ov event to `scrollStop`.
More obvious to name it `scrollStop`, cause imo `end` means like "there is nowhere to scroll anymore".

**Comment by jmarceli** [comment]
That's a good point but if we call property `onScrollEnd` I think that event should also be called `scrollEnd`. Having said so I would opt on renaming the property to stay consistent with v3 API, so the property would be named `onScrollStop` and event would be `scrollStop`. Please tell me what do you think about that, so I can modify my PR.

**Comment by xobotyi** [comment]
@jmarceli I've ment to leave the `scrollStop` name and simply rename the event.  
Ammend the commit and I'll merge it;)

**Comment by xobotyi** [comment]
@jmarceli I've ment to leave the scrollStop name and simply rename the event.
Ammend the commit and I'll merge it;)

**Comment by jmarceli** [comment]
Done, but still, I would consider renaming `onScrollEnd` property to `onScrollStop` to stay consistent

**Comment by jmarceli** [comment]
Refactored according to your recommendation in https://github.com/xobotyi/react-scrollbars-custom/issues/54

**Pull request merged**
